# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OtpMigration.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'OtpMigration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12OtpMigration.proto\"\x86\x01\n\x10MigrationPayload\x12&\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x0e.OtpParameters\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\"\xa2\x01\n\rOtpParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x1d\n\talgorithm\x18\x04 \x01(\x0e\x32\n.Algorithm\x12\x1b\n\x06\x64igits\x18\x05 \x01(\x0e\x32\x0b.DigitCount\x12\x16\n\x04type\x18\x06 \x01(\x0e\x32\x08.OtpType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03*V\n\tAlgorithm\x12\x1e\n\x1a\x41LGORITHM_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04SHA1\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\n\n\x06SHA512\x10\x03\x12\x07\n\x03MD5\x10\x04*=\n\nDigitCount\x12\x1b\n\x17\x44IGIT_COUNT_UNSPECIFIED\x10\x00\x12\x07\n\x03SIX\x10\x01\x12\t\n\x05\x45IGHT\x10\x02*7\n\x07OtpType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OtpMigration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALGORITHM']._serialized_start=324
  _globals['_ALGORITHM']._serialized_end=410
  _globals['_DIGITCOUNT']._serialized_start=412
  _globals['_DIGITCOUNT']._serialized_end=473
  _globals['_OTPTYPE']._serialized_start=475
  _globals['_OTPTYPE']._serialized_end=530
  _globals['_MIGRATIONPAYLOAD']._serialized_start=23
  _globals['_MIGRATIONPAYLOAD']._serialized_end=157
  _globals['_OTPPARAMETERS']._serialized_start=160
  _globals['_OTPPARAMETERS']._serialized_end=322
# @@protoc_insertion_point(module_scope)
